### ISSUE TITLE
2.1.2 from 6th April is broken. 

### ISSUE THREAD

**Issue by tymik** [themebeez/cream-magazine#110]
My site got theme auto updated and it died:
![image](https://user-images.githubusercontent.com/1670525/230682409-33740ef8-7f86-4dc5-85d6-509ec85271d8.png)

```
ParseError thrown
syntax error, unexpected ')'
```
Snipped in addition to the screenshot so the issue is googlable by others.

There's no more info regardless of the full debug.
Nothing in error.log, custom debug log file is not even being created, debug messages are not displayed in the browser.
If I could locate where the issue is, maybe I'd fix it, but as for now my site is broken and I cannot do anything about it

Theme version: 2.1.2 [6th April Update](https://themes.trac.wordpress.org/changeset/188682/cream-magazine)
WP version: 6.2
PHP Version: 7.2

**Comment by Asok17** [comment]
@tymik 

Replace the lines of codes, 269-276, in file inc/class-cream-magazine.php, with the codes below:

```
if ( cream_magazine_has_google_fonts() ) {
	wp_enqueue_style( // phpcs:ignore
		'cream-magazine-fonts',
		cream_magazine_get_google_fonts_url(),
		array(),
		null,
		'all'
	);
}
```
See if this fixes the issue. And let me know.

**Comment by Asok17** [comment]
@tymik 

We have released an update in wordpress.org. Please download it from there and upload it.

Let me know if the error still persists.

**Comment by tymik** [comment]
The error is gone, thanks!

In the meantime I've got an update from the content team that the layout got broken - I asked for some more details, but haven't got a response yet.

Could you tell me where is the layout configuration saved?
Is it in the file system or in the database?

**Comment by Asok17** [comment]
@tymik,

We apologize for the late response. Somehow our support team may have missed it.

Could you elaborate the problem that you have with layout? It would be good if you could share the link of your website too.

**Comment by tymik** [comment]
Unfortunately I cannot get the details - the only feedback I've got so far is more or less:

> everything is broken, it will be easier to change theme and set up a new one from scratch

and I have no idea what has changed and how it has changed :(
I'd really like to have a valuable feedback, but it seems unlikely I will get any.

The original issue in the request was resolved.
