### ISSUE TITLE
Banner / Slider preview

### ISSUE THREAD

**Issue by Gismo1337** [themebeez/cream-magazine#83]
Hey, 
if you change the Itemcounter in Slider Theme Customizer Menu to > 6 it doesn't show Preview Images on Frontpage.

Reproduction: Change to 100

**Comment by h1dd3nsn1p3r** [comment]
![image](https://user-images.githubusercontent.com/21140404/121698072-6118b080-caed-11eb-87eb-860faa9c544b.png)

I just changed the slider image count to 6 & it is working perfectly. 

What do you mean exactly?

**Comment by Gismo1337** [comment]
Hmmm... i am not in the office right now. i check it later again.
At my setup the thumbnails disappeared

Am Fr., 11. Juni 2021 um 16:00 Uhr schrieb Anuj Subedi <
***@***.***>:
